### ISSUE TITLE
ESX.searchinventory Error

### ISSUE THREAD

**Issue by Raikjo** [rumaier/r_drugsales#2]
![Screenshot_4](https://github.com/rumaier/r_drugsales/assets/49317444/71020b50-14ee-420f-99c1-de56d08825fd)

I get these Error if i try to sell drugs, because he cant search for Items in my Inventory

Build 7900
ESX 1.10.5
ox_inventory

**Comment by rumaier** [comment]
Changes were made to the function in 1.10.3, I will update ESX and address this issue.

**Comment by rumaier** [comment]
> ![Screenshot_4](https://private-user-images.githubusercontent.com/49317444/323203618-71020b50-14ee-420f-99c1-de56d08825fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNjc2NzIsIm5iZiI6MTcxMzM2NzM3MiwicGF0aCI6Ii80OTMxNzQ0NC8zMjMyMDM2MTgtNzEwMjBiNTAtMTRlZS00MjBmLTk5YzEtZGU1NmQwODgyNWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDE1MjI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjZGM3YjNlOGMyMDJjYTE4YTg3ZmNmZjZlNTdiMWFmNzdhODhiZmUzMTJlZWRhZGQxMDE5ZDliMDVkMTM3N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BD38Y0KtePV9X-R8JVULKavsiUp4nyBpZVgDK3FX2Lg)
> 
> I get these Error if i try to sell drugs, because he cant search for Items in my Inventory
> 
> Build 7900 ESX 1.10.5 ox_inventory

Download latest update, fixed for ESX 1.10.3+

**Comment by Raikjo** [comment]
works with new update
