### ISSUE TITLE
Money Recieve Issue

### ISSUE THREAD

**Issue by Sonkz0** [rumaier/r_drugsales#3]
on a older version of r_drugsales i was able to receive my "dirty money" as a item however that version had issues. so, I updated to the newest version and now I no longer am able to receive my "dirty money" as a item I get this error: SCRIPT ERROR: @r_drugsales/src/server/main.lua:55: attempt to index a nil value (field 'bulk')**** 
any fix would be greatly appreciated thank you.

**Comment by rumaier** [comment]
@Sonkz0 Open a support ticket in the Discord.
<p>
  <a href="https://discord.gg/r-scripts"><img src="https://github.com/user-attachments/assets/93483cab-6a28-4f4d-88d3-92520a0f81bb"></a>
</p>
