### ISSUE TITLE
Missing local

### ISSUE THREAD

**Issue by Bimby-Boi** [rumaier/r_drugsales#4]
the got_away local is missing
![image](https://github.com/user-attachments/assets/3922b300-dd83-4e76-af39-15940d5682df)

Here's the one I made for en if you want to save yourself the time: 
got_away = 'They got away! RIP those drugs!',

**Comment by rumaier** [comment]
> the got_away local is missing ![image](https://private-user-images.githubusercontent.com/164100440/358874770-3922b300-dd83-4e76-af39-15940d5682df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NDI4NjQsIm5iZiI6MTcyMzk0MjU2NCwicGF0aCI6Ii8xNjQxMDA0NDAvMzU4ODc0NzcwLTM5MjJiMzAwLWRkODMtNGU3Ni1hZjM5LTE1OTQwZDU2ODJkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQwMDU2MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2I5YmY2NDFlMWEwMGMwNmQwNmZiOGZmMWU4YmU4OTg5ZDk2YzY5YTlhODQzNzFiMWQyYTRkYjZmYThkMDZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UkVinYgZgfZ3dxJliF1tYzmbwoTw3tBf5HTWLKzaxsU)
> 
> Here's the one I made for en if you want to save yourself the time: got_away = 'They got away! RIP those drugs!',

Thank you very much, I will get this added in and pushed.
